## 00. Pytorch fundamental

In [44]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [45]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensors
### Creating tensors

In [46]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [47]:
scalar.ndim

0

In [48]:
scalar.item()

7

In [49]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [50]:
vector.ndim

1

In [51]:
vector.shape

torch.Size([2])

In [52]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [53]:
MATRIX.ndim

2

In [54]:
MATRIX[1]

tensor([ 9, 10])

In [55]:
MATRIX.shape

torch.Size([2, 2])

In [56]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]],
                       [[2,3,4],
                        [5,6,7],
                        [8,9,10]]])

In [57]:
TENSOR.ndim

3

In [58]:
TENSOR.shape

torch.Size([2, 3, 3])

In [59]:
TENSOR[0]
TENSOR[1]

tensor([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]])

### Random tensors

In [60]:
#generate random tensor then adjust for best fit data
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3588, 0.3581, 0.8033, 0.9728],
        [0.9849, 0.8183, 0.1970, 0.3881],
        [0.3020, 0.9373, 0.1908, 0.9065]])

In [61]:
random_tensor.ndim

2

In [62]:
# random tensor = image's shape tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones tensors

In [63]:
# Zeros tensor
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [64]:
# Ones tensor
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [65]:
ones.dtype, zeros.dtype
# float32 default type

(torch.float32, torch.float32)

### Creating a range of tensors and tensors like

In [66]:
# Tensors range
one_to_ten = torch.arange(start = 1,end = 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
# Tensors like
zeros_like = torch.zeros_like(input=one_to_ten)
zeros_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [68]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # datatype
                               device=None, # what device (CPU/GPU) is on
                               requires_grad=False) # track gradients or not
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [69]:
#Change dtype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [70]:
float_16_tensor * float_32_tensor
# May or may not error if on dif type

tensor([ 9., 36., 81.])

In [71]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [72]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting information in tensor

 1. Tensors not right datatype - to get datatype from a tensor, can use tensor.dtype
 2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
 3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [73]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5118, 0.8552, 0.6346, 0.3514],
        [0.5707, 0.8813, 0.7810, 0.0788],
        [0.3301, 0.1179, 0.4333, 0.3584]])

In [74]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5118, 0.8552, 0.6346, 0.3514],
        [0.5707, 0.8813, 0.7810, 0.0788],
        [0.3301, 0.1179, 0.4333, 0.3584]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix Multiplication

In [75]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [76]:
tensor * 10

tensor([10, 20, 30])

In [77]:
tensor - 10

tensor([-9, -8, -7])

In [78]:
#Pytorch in-built function
torch.mul(tensor,10) # tensor * 10

tensor([10, 20, 30])

In [79]:
torch.add(tensor,10) # tensor + 10

tensor([11, 12, 13])

### Matrix multiplication
1. element wise mult
2. dot product

In [80]:
# element-wise
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [81]:
# dot product
torch.matmul(tensor,tensor)

tensor(14)

In [82]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 454 µs, sys: 0 ns, total: 454 µs
Wall time: 461 µs


In [83]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 43 µs, sys: 0 ns, total: 43 µs
Wall time: 46.7 µs


tensor(14)

### One of the most common errors in deep learning : shape errors

In [87]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
torch.mm(tensor_A, tensor_B.T) # torch.mm is same as torch.matmul

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Fix error by transpose

In [86]:
tensor_B.T, tensor_B.T.shape, tensor_B, tensor_B.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [88]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape}) <- inner dimensions must match")
print("Output:\n")
output = torch.mm(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")
torch.mm(tensor_A, tensor_B.T)

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) * torch.Size([2, 3])) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Finding the min, max, mean, sum, etc(tensor aggregation)

In [89]:
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [90]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [91]:
torch.max(x), x.max()

(tensor(91), tensor(91))

In [92]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [93]:
torch.sum(x), x.sum()

(tensor(460), tensor(460))

### Finding the positional min and max

In [94]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [95]:
# return the index of the minimum value
x.argmin()

tensor(0)

In [96]:
x[0]

tensor(1)

In [97]:
# return the index of the maximum value
x.argmax()

tensor(9)

In [98]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing, and unsqeezing tensors

In [99]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [102]:
# Add an extra dimension
x_reshaped = x.reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [103]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [104]:
#Changing z changes x because of view
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [105]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [107]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped.T}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [109]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")


Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [111]:
# torch.permute - rearranges the dimension of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels,height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (Selecting data from tensors)

In [113]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [114]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [116]:
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [117]:
x[0][0][0]

tensor(1)

In [118]:
# use ":" to select all
x[:,0]

tensor([[1, 2, 3]])

In [120]:
# Get all values of 0th and 1st dim but only index 1 of 2nd dim
x[:,:,1]

tensor([[2, 5, 8]])

In [121]:
x[:,1,1]

tensor([5])

In [122]:
x[0,0,:]

tensor([1, 2, 3])

In [123]:
# index on x to return 9
x[0,2,2]

tensor(9)

In [124]:
#index on x to return 3, 6,9
x[:,:,2]

tensor([[3, 6, 9]])

## PyTorch tensors & Numpy

In [126]:
array = np.arange(1.0,8.0) #dtype default = float64
tensor = torch.from_numpy(array) #dtype default = float32
array, tensor #dtype = float 64 if not specified when array -> tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [127]:
#Change the value of array, what will this do to 'tensor'?
array = array + 1
array, tensor # change array don't change the tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [128]:
# Tensor -> numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor # all don't share memory

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)
loop of update random number to try and make best fit of data

use seed to reduce randomness

In [129]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2673, 0.3945, 0.9622, 0.6850],
        [0.7536, 0.2695, 0.1625, 0.2625],
        [0.9665, 0.9290, 0.8585, 0.4472]])
tensor([[0.9244, 0.6058, 0.1232, 0.4992],
        [0.0836, 0.7812, 0.3158, 0.4329],
        [0.4462, 0.4677, 0.3431, 0.9392]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [132]:
#Set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # Need to recall each time create new rand
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computation)

#### Getting GPUs
Step 1 : loaded Money

Or use google colab, cloud computing(GCP,AWS,Azure)

### Check for GPU access on PyTorch

In [138]:
torch.cuda.is_available()

False

In [139]:
#Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [141]:
torch.cuda.device_count()

0

## Putting tensors(and models) on the GPU
for more efficient computation

In [143]:
# Create a tensor(default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [144]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3])

In [145]:
# If tensor on GPUs, can't tranform to numpy
# To fix the GPU tensor, can 1st set to the CPU
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu

array([1, 2, 3])